name: Update integration tests

on:
  push:
    branches:
      - master
    paths:
      - docs/test/integration/*/*/pull/*/index.md

jobs:
  update-commit-status:
    runs-on: ubuntu-latest
    name: Update commit status
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0

      - name: Get changed files
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }}..${{ github.event.after }})
          CHANGED_INDEX_FILES=$(echo "$CHANGED_FILES" | grep "docs/test/integration/.*/.*/pull/.*/index.md")
          echo "$CHANGED_INDEX_FILES"
          echo "CHANGED_INDEX_FILES=$CHANGED_INDEX_FILES" >> $GITHUB_ENV

      - name: Update commit status
        run: |
          import os, re
          paths = os.environ.get("CHANGED_INDEX_FILES").splitlines()
          for path in paths:
            print(f"Changed file: {path}")

            with open (path, "r" ) as f:
              file_content = f.read()
              status_search = re.search(r"(?s)^##\s+Status\n\s*(.*?)\s*^#", file_content, flags = re.M)
              if status_search:
                statuses = status_search.group(1)
                active_statuses = re.findall(r"^:.*: (.*)$", statuses)
                print(active_statuses)
        shell: python
